breeds = [
  "Affenpinscher",
  "Afghan Hound",
  "Aidi",
  "Airedale Terrier",
  "Akbash",
  "Akita",
  "Aksaray MalaklisiAlano Español",
  "Alaskan Malamute",
  "AlopekisAlpine Dachsbracke",
  "American Bulldog",
  "American BullyAmerican Cocker Spaniel",
  "American English Coonhound",
  "American Eskimo Dog",
  "American Foxhound",
  "American Hairless Terrier",
  "American Pit Bull Terrier",
  "American Staffordshire Terrier",
  "American Water Spaniel",
  "Appenzeller Sennenhund",
  "Ariegeois",
  "Armant",
  "Armenian Gampr dogArtois Hound",
  "Australian Cattle Dog",
  "Australian Kelpie",
  "Australian Shepherd",
  "Australian Stumpy Tail Cattle Dog",
  "Australian Terrier",
  "Austrian Black and Tan Hound",
  "Austrian Pinscher",
  "Azawakh",
  "Bakharwal dogBanjara Hound",
  "Barbado da Terceira",
  "Barbet",
  "Basenji",
  "Basque Shepherd Dog",
  "Basset Artésien Normand",
  "Basset Bleu de Gascogne",
  "Basset Fauve de Bretagne",
  "Basset Hound",
  "Bavarian Mountain Hound",
  "Beagle",
  "Beagle-Harrier",
  "Belgian Shepherd",
  "Bearded Collie",
  "Beauceron",
  "Bedlington Terrier",
  "Bergamasco Shepherd",
  "Berger Picard",
  "Bernese Mountain Dog",
  "Bichon Frisé",
  "Billy",
  "Black and Tan Coonhound",
  "Black Mouth Cur",
  "Bloodhound",
  "Blue Lacy",
  "Blue Picardy Spaniel",
  "Bluetick Coonhound",
  "BoerboelBohemian Shepherd",
  "Bolognese",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Bosnian Coarse-haired Hound",
  "Boston Terrier",
  "Bouvier des Ardennes",
  "Bouvier des Flandres",
  "Boxer",
  "Boykin Spaniel",
  "Bracco Italiano",
  "Braque d'Auvergne",
  "Braque de l'Ariège",
  "Braque du Bourbonnais",
  "Braque Francais",
  "Braque Saint-Germain",
  "Briard",
  "Briquet Griffon Vendéen",
  "Brittany",
  "Broholmer",
  "Bruno Jura Hound",
  "Brussels Griffon",
  "Bucovina Shepherd Dog",
  "Bull ArabBull Terrier",
  "Bulldog",
  "Bullmastiff",
  "Bully KuttaBurgos Pointer",
  "Ca Mè MallorquíCairn Terrier",
  "Canadian Eskimo Do",
  "Cane Cors",
  "Cão de Castro Laboreiro",
  "Cão de Gado Transmontano",
  "Cão Fila de São Miguel",
  "Cardigan Welsh Corgi",
  "Carea Castellano Manchego",
  "Carea LeonésCarolina Dog",
  "Carpathian Shepherd Do",
  "Catahoula Leopard Do",
  "Catalan Sheepdo",
  "Caucasian Shepherd Do",
  "Cavalier King Charles Spanie",
  "Central Asian Shepherd Do",
  "Cesky Fouse",
  "Cesky Terrie",
  "Chesapeake Bay Retrieve",
  "Chien Français Blanc et Noi",
  "Chien Français Blanc et Orang",
  "Chien Français Tricolor",
  "Chihuahu",
  "Chinook",
  "Chippiparai",
  "Chongqing dogChortai",
  "Chow Chow",
  "Cimarrón UruguayoCirneco dell'Etna",
  "Clumber Spaniel",
  "Colombian fino houndCoton de Tulear",
  "Cretan Hound",
  "Croatian Sheepdo",
  "Curly-Coated Retrieve",
  "Cursin",
  "Czechoslovakian Wolfdog",
  "Dachshund",
  "Dalmatian",
  "Dandie Dinmont Terrier",
  "Danish SpitzDanish-Swedish Farmdog",
  "Denmark Feist",
  "Dogo Argentino",
  "Dogue de Bordeaux",
  "Drentse Patrijshond",
  "Drever",
  "Dunker",
  "Dutch Shepherd",
  "Dutch Smoushond",
  "East Siberian Laika",
  "East European Shepherd",
  "Ecuadorian Hairless Dog",
  "English Cocker Spaniel",
  "English Foxhound",
  "English Mastiff",
  "English Setter",
  "English Shepherd",
  "English Springer Spaniel",
  "English Toy Terrier (Black & Tan)",
  "Entlebucher Mountain Dog",
  "Estonian Hound",
  "Estrela Mountain Do",
  "Eurasier",
  "Field Spaniel",
  "Fila Brasileiro",
  "Finnish Hound",
  "Finnish Lapphund",
  "Finnish Spitz",
  "Flat-Coated Retriever",
  "French Bulldog",
  "French Spaniel",
  "Galgo Español",
  "Garafian Shepherd",
  "Gascon Saintongeoi",
  "German Pinsch",
  "German Roughhaired Pointer",
  "German Shepherd Dog",
  "German Shorthaired Pointer",
  "German Spaniel",
  "German Spitz",
  "German Wirehaired Pointer",
  "Giant Schnauzer",
  "Glen of Imaal Terrier",
  "Golden Retriever",
  "Gończy Polski",
  "Gordon Setter",
  "Grand Anglo-Français Blanc et Noir",
  "Grand Anglo-Français Blanc et Orange",
  "Grand Anglo-Français Tricolore",
  "Grand Basset Griffon Vendéen",
  "Grand Bleu de Gascogne",
  "Grand Griffon Vendée",
  "Great Dane",
  "Greater Swiss Mountain Dog",
  "Greek Harehound",
  "Greek Shepherd",
  "Greenland Dog",
  "Greyhoun",
  "Griffon Bleu de Gascogn",
  "Griffon Fauve de Bretagn",
  "Hanover Hound",
  "Harrier",
  "Havanes",
  "Himalayan Sheepdog",
  "Hierran WolfdogHokkai",
  "Hovawart",
  "Huntaway",
  "Hygen Hound",
  "Ibizan Hound",
  "Icelandic Sheepdog",
  "Irish Setter",
  "Irish Terri",
  "Irish Water Spaniel",
  "Irish Wolfhound",
  "Istrian Coarse-haired Hound",
  "Istrian Shorthaired Houn",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Jagdterrie",
  "Japanese Chin",
  "Japanese Spitz",
  "Japanese Terrier",
  "Jindo",
  "JonangiKai KenKaikadi",
  "Kangal Shepherd D",
  "Kann",
  "Karakachan dogKarelian Bear Dog",
  "Kars",
  "Karst Shepherd",
  "Keeshond",
  "Kerry Beagl",
  "Kerry Blue Terrier",
  "Khala",
  "King Charles Spaniel",
  "King Shepher",
  "KintamaniKishu",
  "KokoniKombai",
  "Komondor",
  "Kooikerhondje",
  "KoolieKoyun dogKromfohrländer",
  "Kuchi",
  "Kuvasz",
  "Labrador Retriever",
  "Lagotto Romagnolo",
  "Lakeland Terrie",
  "Lancashire Heele",
  "Landseer",
  "Lapponian Herder",
  "Large Münsterländer",
  "Leonberger",
  "Levriero SardoLhasa Apso",
  "Lithuanian Hound",
  "Löwchen",
  "Lupo ItalianoMackenzie River huskyMagyar agár",
  "Mahratta Greyhound",
  "Maltes",
  "Manchester Terrier",
  "Maremmano-Abruzzese Sheepdo",
  "Miniature Fox TerrierMiniature Pinsche",
  "Miniature Schnauzer",
  "Mountain Cur",
  "Mountain Feist",
  "MucuchiesMudhol Hound",
  "Mudi",
  "Neapolitan Mastiff",
  "Norfolk Terrie",
  "Norrbottenspets",
  "Northern Inuit DogNorwegian Buhund",
  "Norwegian Elkhound",
  "Norwegian Lundehund",
  "Norwich Terrier",
  "Nova Scotia Duck Tolling Retriever",
  "Old Croatian SighthoundOld Danish Pointer",
  "Old English Sheepdo",
  "Old English Terrier",
  "Olde English Bulldogg",
  "Otterhound",
  "Papillon",
  "Parson Russell Terrier",
  "Pekingese",
  "Pembroke Welsh Corg",
  "Perro de Presa Mallorquin",
  "Peruvian Inca Orchid",
  "Petit Basset Griffon Vendéen",
  "Petit Bleu de Gascogne",
  "Phalène",
  "Pharaoh Hound",
  "Phu Quoc RidgebackPicardy Spaniel",
  "Plummer Terrier",
  "Plott Hound",
  "Podenco Canari",
  "Podenco ValencianoPointer",
  "Poitevin",
  "Polish Greyhound",
  "Polish Hound",
  "Polish Lowland Sheepdog",
  "Polish Tatra Sheepdog",
  "Pomeranian",
  "Pont-Audemer Spaniel",
  "Poodle",
  "Porcelain",
  "Portuguese Podengo",
  "Portuguese Pointer",
  "Portuguese Water Dog",
  "Posavac Hound",
  "Pražský Krysařík",
  "Pshdar dogPudelpointer",
  "Pug",
  "Puli",
  "Pumi",
  "Pungsan dogPyrenean Mastiff",
  "Pyrenean Mountain Dog",
  "Pyrenean Sheepdog",
  "Rafeiro do Alentejo",
  "Rajapalayam",
  "Rampur Greyhoun",
  "Rat Terrier",
  "Rhodesian Ridgeback",
  "Romanian Mioritic Shepherd Do",
  "Romanian Raven Shepherd Do",
  "Rottweiler",
  "Rough Colli",
  "Russian SpanielRussian ToyRusso-European Laika",
  "Ryukyu InuSaarloos Wolfdog",
  "Sabueso Español",
  "Saint Bernard",
  "Saint Hubert Jura Houn",
  "Saint-Usuge SpanielSaluki",
  "Samoyed",
  "SapsaliSarabi dog",
  "Sardinian Shepherd DogŠarplanina",
  "Schapendoe",
  "Schillerstövare",
  "Schipperke",
  "Schweizer Laufhun",
  "Schweizerischer Niederlaufhund",
  "Scottish Deerhound",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Segugio dell'AppenninoSegugio Italiano",
  "Segugio MaremmanoSerbian Hound",
  "Serbian Tricolour Hound",
  "Serrano BulldogShar PeiShetland Sheepdog",
  "Shiba Inu",
  "Shih Tzu",
  "Shikoku",
  "Shiloh Shepherd",
  "Siberian Husky",
  "Silken WindhoundSilky Terrie",
  "Sinhala HoundSkye Terrier",
  "Slough",
  "Slovakian Wirehaired Pointer",
  "Slovenský Cuvac",
  "Slovenský Kopov",
  "Smalandstövare",
  "Small Greek domestic dogSmall Münsterländer",
  "Smooth Collie",
  "Smooth Fox Terrier",
  "Soft-Coated Wheaten Terrier",
  "South Russian Ovcharka",
  "Spanish Mastiff",
  "Spanish Water Dog",
  "Spinone Italian",
  "Sporting Lucas Terrier",
  "Stabyhoun",
  "Staffordshire Bull Terrier",
  "Standard Schnauzer",
  "Stephens Stock",
  "Styrian Coarse-haired Houn",
  "Sussex Spaniel",
  "Swedish Elkhound",
  "Swedish Lapphund",
  "Swedish Vallhun",
  "Swedish White ElkhoundTaigan",
  "Thai Bangkaew DogThai Ridgeback",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Tornjak",
  "Tosa",
  "Toy Fox Terrie",
  "Toy Manchester Terrier",
  "Transylvanian Hound",
  "Treeing CurTreeing Feist",
  "Trigg Hound",
  "Tyrolean Hound",
  "Vikhan",
  "Volpino Italiano",
  "Weimaraner",
  "Welsh SheepdogWelsh Springer Spaniel",
  "Welsh Terrier",
  "West Highland White Terrier",
  "West Siberian Laika",
  "Westphalian Dachsbracke",
  "Wetterhoun",
  "Whippet",
  "White ShepherdWhite Swiss Shepherd Do",
  "Wire Fox Terrier",
  "Wirehaired Pointing Griffon",
  "Yakutian LaikaYorkshire Terrier",
  "Alaunt",
  "Alpine Mastiff",
  "Argentine Polar DogBelgian Mastiff",
  "Black and Tan Terrier",
  "Blue Paul Terrier",
  "Braque Dupuy",
  "Bull and terrierBullenbeisser",
  "Chien-gris",
  "Dalbo dog",
  "Dogo Cubano",
  "Fila da TerceiraGrand Fauve de Bretagn",
  "Halls Heeler",
  "Hare Indian DogHawaiian Poi DogKurī",
  "Tahitian DogTahltan Bear Dog",
  "Talbot Houn",
  "Welsh Hillman",
  ""
]